/** @format */

export const IndustryDetails = [
  {
    id: 1,
    industryname: "Software Development",
    contactperson: "Bret",
    contactnumber: "9120010010",
    employeecount: "45",
    industrytype: "Micro Scale",
    contactemail: "Sincere@april.biz",
    status: "Active",
    image: "https://picsum.photos/id/668/500/500",
  },
  {
    id: 2,
    industryname: "Photo/Videos Movies",
    contactperson: "Antonette",
    contactnumber: "8100345612",
    employeecount: "41",
    industrytype: "Small Scale",
    contactemail: "Shanna@melissa.tv",
    status: "Inactive",
    image: "https://picsum.photos/id/628/500/500",
  },
  {
    id: 3,
    industryname: "IT Services",
    contactperson: "Samantha",
    contactnumber: "8100345612",
    employeecount: "1000",
    industrytype: "Small Scale",
    contactemail: "Nathan@yesenia.net",
    status: "Inactive",
    image: "https://picsum.photos/id/60/500/500",
  },
  {
    id: 4,
    industryname: "Real State",
    contactperson: "Karianne",
    contactnumber: "8100345612",
    employeecount: "500",
    industrytype: "Medium Scale",
    contactemail: "Julianne.OConner@kory.org",
    status: "Inactive",
    image: "https://picsum.photos/id/1048/500/500",
  },
  {
    id: 5,
    industryname: "Resellers",
    contactperson: "Kamren",
    contactnumber: "9123476589",
    employeecount: "55",
    industrytype: "Medium Scale",
    contactemail: "Lucio_Hettinger@annie.ca",
    status: "Active",
    image: "https://picsum.photos/id/1059/500/500",
  },
  {
    id: 6,
    industryname: "UI/UX & Designing",
    contactperson: "Leopoldo_Corkery",
    contactnumber: "9123476589",
    employeecount: "65",
    industrytype: "Large Scale",
    contactemail: "Karley_Dach@jasper.info",
    status: "Active",
    image: "https://picsum.photos/id/180/500/500",
  },
];
